aasemble/django/apps/api/urls.py
from django.conf.urls import include, url

from . import views
from .devel import views as views_devel
from .v1 import views as views_v1
from .v2 import views as views_v2
from .v3 import views as views_v3

urlpatterns = [
    url(r'^events/github/', views.GithubHookView.as_view()),
    url(r'^v1/', include(views_v1.aaSembleV1Views().urls)),
    url(r'^v2/', include(views_v2.aaSembleV2Views().urls)),
    url(r'^v3/', include(views_v3.aaSembleV3Views().urls)),
    url(r'^devel/', include(views_devel.aaSembleDevelViews().urls)),
]

aasemble/django/apps/buildsvc/urls.py
from django.conf.urls import url

import aasemble.django.apps.buildsvc.views

urlpatterns = [
    url(r'^sources/(?P<source_id>\d+)/enable/', aasemble.django.apps.buildsvc.views.enable_source_repo, name='enable_source_repo'),
    url(r'^sources/(?P<source_id>\d+)/rebuild/', aasemble.django.apps.buildsvc.views.rebuild, name='rebuild'),
    url(r'^sources/(?P<source_id>\d+|new)/', aasemble.django.apps.buildsvc.views.package_source, name='package_source'),
    url(r'^sources/', aasemble.django.apps.buildsvc.views.sources, name='sources'),
    url(r'^repositories/', aasemble.django.apps.buildsvc.views.repositories, name='repositories'),
    url(r'^builds/', aasemble.django.apps.buildsvc.views.builds, name='builds'),
    url(r'^external_dependencies/(?P<dependency_uuid>[^/]+|new)/$', aasemble.django.apps.buildsvc.views.external_dependency, name='dependency_definition'),
    url(r'^external_dependencies/', aasemble.django.apps.buildsvc.views.external_dependencies, name='external_dependencies'),
]

aasemble/django/apps/mirrorsvc/urls.py
from django.conf.urls import url

import aasemble.django.apps.mirrorsvc.views

urlpatterns = [
    url(r'^mirrors/(?P<mirror_uuid>[^/]+|new)/$', aasemble.django.apps.mirrorsvc.views.mirror_definition,
        name='mirror_definition'),  # Added before mirrors/ to override next line
    url(r'^mirrors/(?P<mirror_uuid>[^/]+)/refresh/', aasemble.django.apps.mirrorsvc.views.refresh_mirror_with_uuid,
        name='mirror_refresh'),  # Added before mirrors/ to override next line
    url(r'^mirrors/', aasemble.django.apps.mirrorsvc.views.mirrors, name='mirrors'),
    url(r'^snapshots/(?P<snapshot_uuid>[^/]+)/tags/(?P<tag_id>[^/]+|new)', aasemble.django.apps.mirrorsvc.views.snapshot_add_tag, name='snapshot_add_tag'),
    url(r'^snapshots/', aasemble.django.apps.mirrorsvc.views.snapshots, name='snapshots'),
    url(r'^mirrorsets/(?P<uuid>[^/]+|new)/$', aasemble.django.apps.mirrorsvc.views.mirrorset_definition,
        name='mirrorset_definition'),
    url(r'^mirrorsets/(?P<uuid>[^/]+)/snapshots/$', aasemble.django.apps.mirrorsvc.views.mirrorset_snapshots, name='mirrorset_snapshots'),
    url(r'^mirrorsets/(?P<uuid>[^/]+)/snapshots/new', aasemble.django.apps.mirrorsvc.views.create_new_snapshot, name='new_snapshot'),
    url(r'^mirrorsets/', aasemble.django.apps.mirrorsvc.views.mirrorsets, name='mirrorsets'),
]

test_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth.views
import aasemble.django.apps.main.views


urlpatterns = [
    url(r'^api/', include('aasemble.django.apps.api.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/$', aasemble.django.apps.main.views.profile, name='profile'),
    url(r'^$', aasemble.django.apps.main.views.index, name='index'),
    url(r'^buildsvc/', include('aasemble.django.apps.buildsvc.urls', namespace='buildsvc')),
    url(r'^mirrorsvc/', include('aasemble.django.apps.mirrorsvc.urls', namespace='mirrorsvc')),
    url(r'^logout/', django.contrib.auth.views.logout, {'next_page': '/'}, name='logout'),
]

aasemble/django/apps/buildsvc/models/architecture.py
from django.db import models


class Architecture(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.name,)

aasemble/django/apps/buildsvc/models/binary_build.py
from django.db import models


class BinaryBuild(models.Model):
    source_package_version = models.ForeignKey('SourcePackageVersion')
    architecture = models.ForeignKey('Architecture')

    def __str__(self):
        return '%s_%s' % (self.source_package_version, self.architecture)

aasemble/django/apps/buildsvc/models/binary_package.py
from django.db import models


class BinaryPackage(models.Model):
    name = models.CharField(max_length=200)
    repository = models.ForeignKey('Repository')

    def __str__(self):
        return '%s' % (self.name,)

    class Meta:
        unique_together = (('name', 'repository'),)

aasemble/django/apps/buildsvc/models/binary_package_version.py
import hashlib
import os.path

import deb822

from django.core.files.base import File
from django.db import models

from aasemble.django.apps.buildsvc import storage
from aasemble.django.apps.buildsvc.enums import (BINARY_PACKAGE_TYPE_DDEB,
                                                 BINARY_PACKAGE_TYPE_DEB,
                                                 BINARY_PACKAGE_TYPE_UDEB)
from aasemble.django.apps.buildsvc.models.architecture import Architecture
from aasemble.django.apps.buildsvc.models.binary_build import BinaryBuild
from aasemble.django.apps.buildsvc.models.binary_package import BinaryPackage
from aasemble.django.apps.buildsvc.models.binary_package_version_user_field import BinaryPackageVersionUserField
from aasemble.django.apps.buildsvc.models.source_package import SourcePackage
from aasemble.django.apps.buildsvc.models.source_package_version import SourcePackageVersion


def split_description(description):
    if description == '':
        return '', ''

    if '\n' not in description:
        return description, ''

    lines = description.split('\n')
    return lines[0], '\n'.join([l[1:] for l in lines[1:]])


def join_description(short_description, long_description):
    return short_description + (long_description and (''.join(['\n %s' % l for l in long_description.split('\n')])) or '').rstrip(' ')


def _extract_info_from_deb(path):
    from aasemble.utils import run_cmd
    out = run_cmd(['dpkg-deb', '-I', path, 'control'])
    return deb822.Deb822(out)


class BinaryPackageVersion(models.Model):
    BINARY_PACKAGE_TYPE_CHOICES = ((BINARY_PACKAGE_TYPE_DEB, 'Debian package (.deb)'),
                                   (BINARY_PACKAGE_TYPE_UDEB, 'Debian-installer package (.udeb)'),
                                   (BINARY_PACKAGE_TYPE_DDEB, 'Debug Debian package (.ddeb)'))
    binary_package = models.ForeignKey(BinaryPackage)
    short_description = models.CharField(max_length=255, null=False, default='')
    long_description = models.TextField(null=False, default="")
    binary_build = models.ForeignKey(BinaryBuild)
    package_type = models.SmallIntegerField(choices=BINARY_PACKAGE_TYPE_CHOICES, default=BINARY_PACKAGE_TYPE_DEB)

    # Well-known fields
    version = models.CharField(max_length=200, null=False)
    architecture = models.CharField(max_length=32)
    maintainer = models.TextField(null=True)
    installed_size = models.IntegerField(null=True)
    depends = models.TextField(null=True)
    recommends = models.TextField(null=True)
    suggests = models.TextField(null=True)
    conflicts = models.TextField(null=True)
    replaces = models.TextField(null=True)
    provides = models.TextField(null=True)
    pre_depends = models.TextField(null=True)
    enhances = models.TextField(null=True)
    breaks = models.TextField(null=True)
    priority = models.TextField(null=True)
    section = models.TextField(null=True)
    homepage = models.CharField(max_length=250)

    # "Fileinfo" fields
    size = models.IntegerField()
    md5sum = models.CharField(max_length=32)
    sha1 = models.CharField(max_length=40)
    sha256 = models.CharField(max_length=64)

    # Not used? wtf?
    location = models.CharField(max_length=250)

    # Fields that are part of the model.
    model_fields = ('Version',
                    'Architecture',
                    'Maintainer',
                    'Installed-Size',
                    'Depends',
                    'Recommends',
                    'Suggests',
                    'Conflicts',
                    'Replaces',
                    'Provides',
                    'Pre-Depends',
                    'Enhances',
                    'Breaks',
                    'Priority',
                    'Section',
                    'Homepage')

    # Fields that have to do with the file itself
    fileinfo_fields = ('Size',
                       'Filename',
                       'MD5sum',
                       'SHA1',
                       'SHA256')

    # Fields that are derived from other data and thus should
    # just be ignored if read from the package (otherwise they'd
    # wind up as user fields and get included twice).
    generated_fields = ('Package',
                        'Source',
                        'Filename')

    def __str__(self):
        return '%s_%s_%s' % (self.binary_package.name, self.version, self.binary_build.architecture)

    @property
    def filename(self):
        sp = self.binary_build.source_package_version.source_package
        return 'pool/main/%s/%s/%s_%s_%s.deb' % (sp.name[0], sp.name, self.binary_package.name, self.version, self.architecture)

    def format_for_packages(self):
        data = deb822.Deb822()

        data['Package'] = self.binary_package.name
        data['Source'] = self.binary_build.source_package_version.source_package.name

        for field in self.model_fields:
            value = getattr(self, field.lower().replace('-', '_'))
            if value:
                data[field] = str(value)

        data['Filename'] = self.filename

        for field in self.fileinfo_fields:
            data[field] = str(getattr(self, field.lower().replace('-', '_')))

        data['Description'] = join_description(self.short_description, self.long_description)
        for bpvuf in self.binarypackageversionuserfield_set.all():
            data[bpvuf.name] = bpvuf.value
        return str(data)

    def store(self, fpath):
        destpath = os.path.join(self.binary_build.source_package_version.source_package.repository.user.username,
                                self.binary_build.source_package_version.source_package.repository.name,
                                self.filename)
        storage_driver = storage.get_repository_storage_driver()
        with open(fpath, 'rb') as fp:
            storage_driver.save(destpath, File(fp))

    @classmethod
    def import_file(cls, series, path, source_package_version=None):
        control = _extract_info_from_deb(path)

        bb_info = {'source_package': None,
                   'version': None,
                   'architecture': None}

        model_fields_lowercase = [f.lower() for f in cls.model_fields]
        ignored_fields_lowercase = [f.lower() for f in (cls.fileinfo_fields + cls.generated_fields)]

        user_fields = []
        kwargs = {}
        for k in control:
            k_lower = k.lower()
            if k_lower == 'package':
                bp, _ = BinaryPackage.objects.get_or_create(name=control[k], repository=series.repository)
                kwargs['binary_package'] = bp
            elif k_lower == 'source':
                bb_info['source_package'], _ = SourcePackage.objects.get_or_create(name=control[k], repository=series.repository)
            elif k_lower == 'version':
                kwargs['version'] = control[k]
                bb_info['version'] = control[k]
            elif k_lower == 'architecture':
                bb_info['architecture'] = Architecture.objects.get(name=control[k])
                kwargs['architecture'] = control[k]
            elif k_lower in model_fields_lowercase:
                kwargs[k.lower().replace('-', '_')] = control[k]
            elif k_lower == 'description':
                kwargs['short_description'], kwargs['long_description'] = split_description(control[k])
            elif k_lower not in ignored_fields_lowercase:
                user_fields += [BinaryPackageVersionUserField(k, control[k])]

        if not bb_info['source_package']:
            bb_info['source_package'], _ = SourcePackage.objects.get_or_create(name=path.split('/')[-2], repository=series.repository)

        if all(bb_info.values()):
            if not source_package_version:
                spv, _ = SourcePackageVersion.objects.get_or_create(source_package=bb_info['source_package'], version=bb_info['version'])
            else:
                spv = source_package_version
            kwargs['binary_build'], _ = BinaryBuild.objects.get_or_create(source_package_version=spv, architecture=bb_info['architecture'])

        with open(path, 'rb') as fp:
            contents = fp.read()

        kwargs['md5sum'] = hashlib.md5(contents).hexdigest()
        kwargs['sha1'] = hashlib.sha1(contents).hexdigest()
        kwargs['sha256'] = hashlib.sha256(contents).hexdigest()
        kwargs['size'] = len(contents)

        self, _ = cls.objects.get_or_create(**kwargs)
        self.store(path)

        series.binary_package_versions.add(self)

        for user_field in user_fields:
            user_field.binary_package_version = self
            user_field.save()

aasemble/django/apps/buildsvc/models/binary_package_version_user_field.py
from django.db import models


class BinaryPackageVersionUserField(models.Model):
    binary_package_version = models.ForeignKey('BinaryPackageVersion')
    name = models.CharField(max_length=100)
    value = models.TextField()

    class Meta:
        order_with_respect_to = 'binary_package_version'

aasemble/django/apps/buildsvc/models/external_dependency.py
import uuid

from django.db import models


class ExternalDependency(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    url = models.URLField()
    series = models.CharField(max_length=200)
    components = models.CharField(max_length=200, null=True, blank=True)
    own_series = models.ForeignKey('Series')
    key = models.TextField()

    @property
    def deb_line(self):
        return '\n'.join(self.deb_lines)

    @property
    def deb_lines(self):
        return ['deb %s %s %s' % (self.url, series, self.components) for series in self.series.split(' ')]

    def user_can_modify(self, user):
        return self.own_series.user_can_modify(user)

    @classmethod
    def lookup_by_user(cls, user):
        if not user.is_active:
            return cls.objects.none()
        if user.is_superuser:
            return cls.objects.all()
        return cls.objects.filter(own_series__repository__user=user) | cls.objects.filter(own_series__repository__extra_admins__in=user.groups.all())

aasemble/django/apps/buildsvc/models/series.py
import uuid

from django.db import models
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Series(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    repository = models.ForeignKey('Repository', related_name='series')
    source_package_versions = models.ManyToManyField('SourcePackageVersion')
    binary_package_versions = models.ManyToManyField('BinaryPackageVersion')

    def __str__(self):
        return '%s/%s' % (self.repository.name, self.name)

    def binary_source_list(self, force_trusted=False):
        return self._source_list(prefix='deb', force_trusted=force_trusted)

    def source_source_list(self, force_trusted=False):
        return self._source_list(prefix='deb-src', force_trusted=force_trusted)

    def _source_list(self, prefix, force_trusted=False):
        if force_trusted:
            option = ' [trusted=yes]'
        else:
            option = ''
        return '%s%s %s %s main' % (prefix,
                                    option,
                                    self.repository.base_url,
                                    self.name)

    class Meta:
        verbose_name_plural = 'series'

    def process_changes(self, changes_file):
        self.repository.process_changes(self.name, changes_file)

    def import_deb(self, path):
        self.repository.import_deb(self.name, path)

    def import_dsc(self, path):
        self.repository.import_dsc(self.name, path)

    def build_sources_list(self):
        sources = []
        for series in ('trusty', 'trusty-updates', 'trusty-security'):
            sources += ['deb http://archive.ubuntu.com/ubuntu {} main universe restricted multiverse'.format(series)]
        sources += [self.binary_source_list(force_trusted=True)]
        sources += sum([extdep.deb_lines for extdep in self.externaldependency_set.all()], [])
        return '\n'.join(sources)

    def build_apt_keys(self):
        keys = [self.repository.key_data]
        keys += [extdep.key for extdep in self.externaldependency_set.all()]
        return '\n'.join(keys)

    def export(self):
        self.repository.export()

    def user_can_modify(self, user):
        return self.repository.user_can_modify(user)

aasemble/django/apps/buildsvc/forms.py
from django.forms import ModelForm

from aasemble.django.apps.buildsvc.models import ExternalDependency, PackageSource


class PackageSourceForm(ModelForm):
    class Meta:
        model = PackageSource
        fields = ['git_url', 'branch', 'series']


class ExternalDependencyForm(ModelForm):
    class Meta:
        model = ExternalDependency
        fields = ['url', 'series', 'components', 'own_series', 'key']

aasemble/django/apps/main/templates/aasemble/base.html
{% extends 'bootstrap3/bootstrap3.html' %}
{% load bootstrap3 %}
{% load static from staticfiles %}


{% block bootstrap3_extra_head %}
    <link href="{% static "aasemble/main/dashboard.css" %}" rel="stylesheet">
{% endblock %}

{% block bootstrap3_title %}{{ title }}{% endblock %}
{% block bootstrap3_content %}

    <!-- Custom styles for this template -->

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">{{ title }}</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          {% if request.user.is_authenticated %}
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/">Dashboard</a></li>
            <li><a href="{% url "buildsvc:repositories" %}">Repositories</a></li>
            <li><a href="{% url "buildsvc:sources" %}">Sources</a></li>
            <li><a href="{% url "buildsvc:builds" %}">Builds</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="{% url "profile" %}">Profile</a></li>
            <li><a href="#">Help</a></li>
            <li><a href="/logout">Log out</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      {% block aasemble_container %}
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar" >
            <li><a href="{% url "index" %}">Overview <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url "buildsvc:repositories" %}">Repositories</a></li>
            <li><a href="{% url "buildsvc:sources" %}">Sources</a></li>
            <li><a href="{% url "buildsvc:builds" %}">Builds</a></li>
            <li><a href="{% url "buildsvc:external_dependencies" %}">External Dependencies</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="{% url "mirrorsvc:mirrors" %}">Mirrors</a></li>
            <li><a href="{% url "mirrorsvc:mirrorsets" %}">Mirror-Sets</a></li>
            <li><a href="{% url "mirrorsvc:snapshots" %}">Snapshots</a></li>
          </ul>
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">{% block title %}Dashboard{% endblock %}</h1>
          {% block aasemble_content %}

          <div class="row placeholders">
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/sky" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
            <div class="col-xs-6 col-sm-3 placeholder">
              <img data-src="holder.js/200x200/auto/vine" class="img-responsive" alt="Generic placeholder thumbnail">
              <h4>Label</h4>
              <span class="text-muted">Something else</span>
            </div>
          </div>

          <h2 class="sub-header">Section title</h2>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                  <th>Header</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>1,001</td>
                  <td>Lorem</td>
                  <td>ipsum</td>
                  <td>dolor</td>
                  <td>sit</td>
                </tr>
                <tr>
                  <td>1,002</td>
                  <td>amet</td>
                  <td>consectetur</td>
                  <td>adipiscing</td>
                  <td>elit</td>
                </tr>
              </tbody>
            </table>
          </div>
        {% endblock %}

        {% bootstrap_messages %}

    </div>
  {% endblock %}

{% endblock %}
{% block bootstrap3_extra_script %}
  <script>
    $('li').has('a[href="{{ request.path }}"]').addClass('active');
  </script>
{% endblock %}

aasemble/django/apps/main/templates/aasemble/dashboard.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block content %}{% endblock %}
{% block aasemble_content %}
<p>There will be some sort of overview page here</p>
{% endblock %}

aasemble/django/apps/main/templates/aasemble/front.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block aasemble_container %}
<div class="jumbotron">
  <h1>Welcome to {{ title }}</h1>
  <p>There's not much to see here without logging in...</p>
  <p><a class="btn btn-primary btn-lg" href="/accounts/github/login/" role="button" id="login_button">Log in</a></p>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h2>Package building</h2>
      <p>Choose any of your repositories on Github and have our package building service turn it into Debian packages.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Mirrors and snapshots</h2>
      <p>Mirror any APT repository and create versioned snapshots of your mirror collection. Using snapshots lets you test updates before tested before being pushed to production.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
   </div>
<!--    <div class="col-md-4">
      <h2>Upgrade orchestration</h2>
      <p>Describe your upgrade sequence and use our web service to orchestrate your upgrade rollout. We'll help ensure things get upgraded in the correct order and in a way that lets your service stay up during the upgrade.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Deployment Engine</h2>
      <p>Use our deployment engine to not just deploy your application, but also provision the infrastructure to host it.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Deployment Engine</h2>
      <p>Use our deployment engine to not just deploy your application, but also provision the infrastructure to host it.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-md-4">
      <h2>Host Agent</h2>
      <p>Our host agent runs on every host, provides near real-time monitoring, alerting, service discovery and integration with our upgrade orchestration service.</p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div> -->
  </div>
  
  <hr>
  <footer>
    <p>&copy; {{ title }} 2015</p>
  </footer>
</div>

{% endblock %}

aasemble/django/apps/main/templates/aasemble/profile.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}Profile{% endblock %}
{% block aasemble_content %}
  <dl class="dl-horizontal">
    <dt>Username:</dt>
    <dd>{{ user.username }}</dd>
    <dt>Github username:</dt>
    <dd>{{ user.username }}</dd>
    <dt>Auth token (for API):</dt>
    <dd>{{ user.auth_token }}</dd>
  </dl>
{% endblock %}