aasemble/django/apps/buildsvc/urls.py
from django.conf.urls import url

import aasemble.django.apps.buildsvc.views

urlpatterns = [
    url(r'^sources/(?P<source_id>\d+)/enable/', aasemble.django.apps.buildsvc.views.enable_source_repo, name='enable_source_repo'),
    url(r'^sources/(?P<source_id>\d+)/rebuild/', aasemble.django.apps.buildsvc.views.rebuild, name='rebuild'),
    url(r'^sources/(?P<source_id>\d+|new)/', aasemble.django.apps.buildsvc.views.package_source, name='package_source'),
    url(r'^sources/', aasemble.django.apps.buildsvc.views.sources, name='sources'),
    url(r'^repositories/', aasemble.django.apps.buildsvc.views.repositories, name='repositories'),
    url(r'^builds/', aasemble.django.apps.buildsvc.views.builds, name='builds'),
    url(r'^external_dependencies/(?P<dependency_uuid>[^/]+|new)/$', aasemble.django.apps.buildsvc.views.external_dependency, name='dependency_definition'),
    url(r'^external_dependencies/', aasemble.django.apps.buildsvc.views.external_dependencies, name='external_dependencies'),
]

test_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth.views
import aasemble.django.apps.main.views


urlpatterns = [
    url(r'^api/', include('aasemble.django.apps.api.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/$', aasemble.django.apps.main.views.profile, name='profile'),
    url(r'^$', aasemble.django.apps.main.views.index, name='index'),
    url(r'^buildsvc/', include('aasemble.django.apps.buildsvc.urls', namespace='buildsvc')),
    url(r'^mirrorsvc/', include('aasemble.django.apps.mirrorsvc.urls', namespace='mirrorsvc')),
    url(r'^logout/', django.contrib.auth.views.logout, {'next_page': '/'}, name='logout'),
]

aasemble/django/apps/buildsvc/models/architecture.py
from django.db import models


class Architecture(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return '%s' % (self.name,)

aasemble/django/apps/buildsvc/models/binary_build.py
from django.db import models


class BinaryBuild(models.Model):
    source_package_version = models.ForeignKey('SourcePackageVersion')
    architecture = models.ForeignKey('Architecture')

    def __str__(self):
        return '%s_%s' % (self.source_package_version, self.architecture)

aasemble/django/apps/buildsvc/models/binary_package.py
from django.db import models


class BinaryPackage(models.Model):
    name = models.CharField(max_length=200)
    repository = models.ForeignKey('Repository')

    def __str__(self):
        return '%s' % (self.name,)

    class Meta:
        unique_together = (('name', 'repository'),)

aasemble/django/apps/buildsvc/models/binary_package_version.py
import hashlib
import os.path

import deb822

from django.core.files.base import File
from django.db import models

from aasemble.django.apps.buildsvc import storage
from aasemble.django.apps.buildsvc.enums import (BINARY_PACKAGE_TYPE_DDEB,
                                                 BINARY_PACKAGE_TYPE_DEB,
                                                 BINARY_PACKAGE_TYPE_UDEB)
from aasemble.django.apps.buildsvc.models.architecture import Architecture
from aasemble.django.apps.buildsvc.models.binary_build import BinaryBuild
from aasemble.django.apps.buildsvc.models.binary_package import BinaryPackage
from aasemble.django.apps.buildsvc.models.binary_package_version_user_field import BinaryPackageVersionUserField
from aasemble.django.apps.buildsvc.models.source_package import SourcePackage
from aasemble.django.apps.buildsvc.models.source_package_version import SourcePackageVersion


def split_description(description):
    if description == '':
        return '', ''

    if '\n' not in description:
        return description, ''

    lines = description.split('\n')
    return lines[0], '\n'.join([l[1:] for l in lines[1:]])


def join_description(short_description, long_description):
    return short_description + (long_description and (''.join(['\n %s' % l for l in long_description.split('\n')])) or '').rstrip(' ')


def _extract_info_from_deb(path):
    from aasemble.utils import run_cmd
    out = run_cmd(['dpkg-deb', '-I', path, 'control'])
    return deb822.Deb822(out)


class BinaryPackageVersion(models.Model):
    BINARY_PACKAGE_TYPE_CHOICES = ((BINARY_PACKAGE_TYPE_DEB, 'Debian package (.deb)'),
                                   (BINARY_PACKAGE_TYPE_UDEB, 'Debian-installer package (.udeb)'),
                                   (BINARY_PACKAGE_TYPE_DDEB, 'Debug Debian package (.ddeb)'))
    binary_package = models.ForeignKey(BinaryPackage)
    short_description = models.CharField(max_length=255, null=False, default='')
    long_description = models.TextField(null=False, default="")
    binary_build = models.ForeignKey(BinaryBuild)
    package_type = models.SmallIntegerField(choices=BINARY_PACKAGE_TYPE_CHOICES, default=BINARY_PACKAGE_TYPE_DEB)

    # Well-known fields
    version = models.CharField(max_length=200, null=False)
    architecture = models.CharField(max_length=32)
    maintainer = models.TextField(null=True)
    installed_size = models.IntegerField(null=True)
    depends = models.TextField(null=True)
    recommends = models.TextField(null=True)
    suggests = models.TextField(null=True)
    conflicts = models.TextField(null=True)
    replaces = models.TextField(null=True)
    provides = models.TextField(null=True)
    pre_depends = models.TextField(null=True)
    enhances = models.TextField(null=True)
    breaks = models.TextField(null=True)
    priority = models.TextField(null=True)
    section = models.TextField(null=True)
    homepage = models.CharField(max_length=250)

    # "Fileinfo" fields
    size = models.IntegerField()
    md5sum = models.CharField(max_length=32)
    sha1 = models.CharField(max_length=40)
    sha256 = models.CharField(max_length=64)

    # Not used? wtf?
    location = models.CharField(max_length=250)

    # Fields that are part of the model.
    model_fields = ('Version',
                    'Architecture',
                    'Maintainer',
                    'Installed-Size',
                    'Depends',
                    'Recommends',
                    'Suggests',
                    'Conflicts',
                    'Replaces',
                    'Provides',
                    'Pre-Depends',
                    'Enhances',
                    'Breaks',
                    'Priority',
                    'Section',
                    'Homepage')

    # Fields that have to do with the file itself
    fileinfo_fields = ('Size',
                       'Filename',
                       'MD5sum',
                       'SHA1',
                       'SHA256')

    # Fields that are derived from other data and thus should
    # just be ignored if read from the package (otherwise they'd
    # wind up as user fields and get included twice).
    generated_fields = ('Package',
                        'Source',
                        'Filename')

    def __str__(self):
        return '%s_%s_%s' % (self.binary_package.name, self.version, self.binary_build.architecture)

    @property
    def filename(self):
        sp = self.binary_build.source_package_version.source_package
        return 'pool/main/%s/%s/%s_%s_%s.deb' % (sp.name[0], sp.name, self.binary_package.name, self.version, self.architecture)

    def format_for_packages(self):
        data = deb822.Deb822()

        data['Package'] = self.binary_package.name
        data['Source'] = self.binary_build.source_package_version.source_package.name

        for field in self.model_fields:
            value = getattr(self, field.lower().replace('-', '_'))
            if value:
                data[field] = str(value)

        data['Filename'] = self.filename

        for field in self.fileinfo_fields:
            data[field] = str(getattr(self, field.lower().replace('-', '_')))

        data['Description'] = join_description(self.short_description, self.long_description)
        for bpvuf in self.binarypackageversionuserfield_set.all():
            data[bpvuf.name] = bpvuf.value
        return str(data)

    def store(self, fpath):
        destpath = os.path.join(self.binary_build.source_package_version.source_package.repository.user.username,
                                self.binary_build.source_package_version.source_package.repository.name,
                                self.filename)
        storage_driver = storage.get_repository_storage_driver()
        with open(fpath, 'rb') as fp:
            storage_driver.save(destpath, File(fp))

    @classmethod
    def import_file(cls, series, path, source_package_version=None):
        control = _extract_info_from_deb(path)

        bb_info = {'source_package': None,
                   'version': None,
                   'architecture': None}

        model_fields_lowercase = [f.lower() for f in cls.model_fields]
        ignored_fields_lowercase = [f.lower() for f in (cls.fileinfo_fields + cls.generated_fields)]

        user_fields = []
        kwargs = {}
        for k in control:
            k_lower = k.lower()
            if k_lower == 'package':
                bp, _ = BinaryPackage.objects.get_or_create(name=control[k], repository=series.repository)
                kwargs['binary_package'] = bp
            elif k_lower == 'source':
                bb_info['source_package'], _ = SourcePackage.objects.get_or_create(name=control[k], repository=series.repository)
            elif k_lower == 'version':
                kwargs['version'] = control[k]
                bb_info['version'] = control[k]
            elif k_lower == 'architecture':
                bb_info['architecture'] = Architecture.objects.get(name=control[k])
                kwargs['architecture'] = control[k]
            elif k_lower in model_fields_lowercase:
                kwargs[k.lower().replace('-', '_')] = control[k]
            elif k_lower == 'description':
                kwargs['short_description'], kwargs['long_description'] = split_description(control[k])
            elif k_lower not in ignored_fields_lowercase:
                user_fields += [BinaryPackageVersionUserField(k, control[k])]

        if not bb_info['source_package']:
            bb_info['source_package'], _ = SourcePackage.objects.get_or_create(name=path.split('/')[-2], repository=series.repository)

        if all(bb_info.values()):
            if not source_package_version:
                spv, _ = SourcePackageVersion.objects.get_or_create(source_package=bb_info['source_package'], version=bb_info['version'])
            else:
                spv = source_package_version
            kwargs['binary_build'], _ = BinaryBuild.objects.get_or_create(source_package_version=spv, architecture=bb_info['architecture'])

        with open(path, 'rb') as fp:
            contents = fp.read()

        kwargs['md5sum'] = hashlib.md5(contents).hexdigest()
        kwargs['sha1'] = hashlib.sha1(contents).hexdigest()
        kwargs['sha256'] = hashlib.sha256(contents).hexdigest()
        kwargs['size'] = len(contents)

        self, _ = cls.objects.get_or_create(**kwargs)
        self.store(path)

        series.binary_package_versions.add(self)

        for user_field in user_fields:
            user_field.binary_package_version = self
            user_field.save()

aasemble/django/apps/buildsvc/models/binary_package_version_user_field.py
from django.db import models


class BinaryPackageVersionUserField(models.Model):
    binary_package_version = models.ForeignKey('BinaryPackageVersion')
    name = models.CharField(max_length=100)
    value = models.TextField()

    class Meta:
        order_with_respect_to = 'binary_package_version'

aasemble/django/apps/buildsvc/models/source_package.py
from django.db import models


class SourcePackage(models.Model):
    name = models.CharField(max_length=200)
    repository = models.ForeignKey('Repository')

    def __str__(self):
        return '%s' % (self.name,)

    @property
    def directory(self):
        return 'pool/main/%s/%s' % (self.name[0], self.name)

    class Meta:
        unique_together = (('name', 'repository'),)

aasemble/django/apps/buildsvc/models/source_package_version_user_field.py
from django.db import models


class SourcePackageVersionUserField(models.Model):
    source_package_version = models.ForeignKey('SourcePackageVersion')
    name = models.CharField(max_length=100)
    value = models.TextField()

    class Meta:
        order_with_respect_to = 'source_package_version'

aasemble/django/apps/buildsvc/forms.py
from django.forms import ModelForm

from aasemble.django.apps.buildsvc.models import ExternalDependency, PackageSource


class PackageSourceForm(ModelForm):
    class Meta:
        model = PackageSource
        fields = ['git_url', 'branch', 'series']


class ExternalDependencyForm(ModelForm):
    class Meta:
        model = ExternalDependency
        fields = ['url', 'series', 'components', 'own_series', 'key']

aasemble/django/apps/buildsvc/views.py
import logging

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render

from .forms import ExternalDependencyForm, PackageSourceForm
from .models import Build, ExternalDependency, PackageSource, Repository, Series

LOG = logging.getLogger(__name__)


def get_package_source_form(request, *args, **kwargs):
    form = PackageSourceForm(*args, **kwargs)

    sqs = Series.objects.filter(repository__in=Repository.lookup_by_user(request.user))

    form.fields['series'].queryset = sqs

    return form


@login_required
def package_source(request, source_id):
    if source_id == 'new':
        ps = None
    else:
        ps = PackageSource.objects.get(pk=source_id)
        if not ps.series.user_can_modify(request.user):
            ps, source_id = None, 'new'

    if request.method == 'POST':
        form = get_package_source_form(request, request.POST, instance=ps)

        if ps is not None and request.POST.get('delete', '') == 'delete':
            ps.delete()
            return HttpResponseRedirect(reverse('buildsvc:sources'))

        if ((form.is_valid() and
             form.cleaned_data['series'].user_can_modify(request.user))):
            ps = form.save()
            ps.register_webhook()
            return HttpResponseRedirect(reverse('buildsvc:sources'))
    else:
        form = get_package_source_form(request, instance=ps)

    return render(request, 'buildsvc/html/package_source.html',
                  {'form': form, 'source_id': source_id})


def get_external_dependency_form(request, *args, **kwargs):
    form = ExternalDependencyForm(*args, **kwargs)

    return form


@login_required
def external_dependency(request, dependency_uuid):
    if dependency_uuid == 'new':
        dependency = None
    else:
        dependency = ExternalDependency.objects.get(uuid=dependency_uuid)
        if not dependency.user_can_modify(request.user):
            dependency, dependency_uuid = None, 'new'

    if request.method == 'POST':
        form = get_external_dependency_form(request, request.POST, instance=dependency)

        if dependency is not None and request.POST.get('delete', '') == 'delete':
            dependency.delete()
            return HttpResponseRedirect(reverse('buildsvc:external_dependencies'))

        if ((form.is_valid() and
             form.cleaned_data['own_series'].user_can_modify(request.user))):
            form.save()
            return HttpResponseRedirect(reverse('buildsvc:external_dependencies'))
    else:
        form = get_external_dependency_form(request, instance=dependency)

    return render(request, 'buildsvc/html/external_dependency_definition.html',
                  {'form': form, 'dependency_uuid': dependency_uuid})


@login_required
def enable_source_repo(request, source_id):
    try:
        ps = PackageSource.objects.get(id=source_id)
        if ps.user_can_modify(request.user):
            ps.disabled = False
            ps.save()
    except ObjectDoesNotExist:
        LOG.debug('Could not find source repo with source_id %s. Repo still disabled.' % source_id)

    return HttpResponseRedirect(reverse('buildsvc:sources'))


@login_required
def sources(request):
    sources = PackageSource.objects.filter(series__repository__in=Repository.lookup_by_user(request.user))
    return render(request, 'buildsvc/html/sources.html', {'sources': sources})


@login_required
def builds(request):
    builds = Build.objects.filter(source__series__repository__in=Repository.lookup_by_user(request.user)).order_by('-build_started')
    return render(request, 'buildsvc/html/builds.html', {'builds': builds})


@login_required
def rebuild(request, source_id):
    ps = PackageSource.objects.get(pk=source_id)
    if ps.series.user_can_modify(request.user):
        try:
            ps.build()
        except Exception:
            # will handle it later
            pass
        return render(request, 'buildsvc/html/rebuild.html', {'source': ps})
    else:
        return HttpResponseRedirect(reverse('buildsvc:sources'))


@login_required
def repositories(request):
    repositories = Repository.lookup_by_user(request.user)
    return render(request, 'buildsvc/html/repositories.html',
                  {'repositories': repositories, 'settings': settings})


@login_required
def external_dependencies(request):
    dependencies = ExternalDependency.lookup_by_user(request.user)
    return render(request, 'buildsvc/html/external_dependencies.html', {'dependencies': dependencies})

aasemble/django/apps/buildsvc/templates/buildsvc/html/builds.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}
{% load humanize %}

{% block title %}Builds{% endblock %}
{% block aasemble_content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Repository</th>
          <th>Source</th>
          <th>Version</th>
          <th>Build started</th>
          <th>Build finished</th>
          <th>Build duration (sec)</th>
          <th>Build log</th>
        </tr>
      </thead>
      <tbody>
        {% for build in builds %}
        <tr>
          <td>{{ build.source.series.repository.name }}</td>
          <td>{{ build.source.name }}</td>
          <td>{{ build.version }}</td>
          <td>{{ build.build_started|naturaltime }}</td>
          <td>{{ build.build_finished|naturaltime }}</td>
          <td>{{ build.duration }}</td>
          <td><a href="{{ build.buildlog_url }}">Build log</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

aasemble/django/apps/buildsvc/templates/buildsvc/html/external_dependencies.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}External Dependencies{% endblock %}
{% block aasemble_content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>&nbsp;</th>
          <th>UUID</th>
          <th>External APT Repo</th>
          <th>Dependency for</th>
          <th>Key</th>
        </tr>
      </thead>
      <tbody>
        {% for dependency in dependencies %}
        <tr>
          <td><small><a href="{% url "buildsvc:dependency_definition" dependency_uuid=dependency.uuid %}">{% bootstrap_icon "pencil" %}</a></small></td>
          <td>{{ dependency.uuid }}</td>
          <td>{{ dependency.deb_line }}</td>
          <td>{{ dependency.own_series }}</td>
          <td>{{ dependency.key }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <a class="btn btn-primary" href="{% url "buildsvc:dependency_definition" dependency_uuid='new' %}" role="button">{% bootstrap_icon "plus" %} New</a>
{% endblock %}

aasemble/django/apps/buildsvc/templates/buildsvc/html/external_dependency_definition.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}
{% block title %}
    {% if dependency_uuid != 'new' %}
        Edit External Dependency
    {% else %}
        Add new External Dependency
    {% endif %}
{% endblock %}
{% block aasemble_content %}
<form action="{% url "buildsvc:dependency_definition" dependency_uuid=dependency_uuid %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
        {% if mirror_id != 'new' %}
            <button type="submit" class="btn btn-danger" name="delete" value="delete">
                 Delete
            </button>
        {% endif %}
    {% endbuttons %}
{% endblock %}

aasemble/django/apps/buildsvc/templates/buildsvc/html/package_source.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}
{% block title %}
    {% if source_id != 'new' %}
        Edit Package Source
    {% else %}
        Package Source
    {% endif %}
{% endblock %}
{% block aasemble_content %}
<form action="{% url "buildsvc:package_source" source_id=source_id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
        {% if source_id != 'new' %}
            <button type="submit" class="btn btn-danger" name="delete" value="delete">
                 Delete
            </button>
        {% endif %}
    {% endbuttons %}
{% endblock %}

aasemble/django/apps/buildsvc/templates/buildsvc/html/rebuild.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}
{% block title %}
    Rebuilding source repo {{ source.name }}
{% endblock %}
{% block aasemble_content %} {% endblock %}

aasemble/django/apps/buildsvc/templates/buildsvc/html/repositories.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}APT repositories{% endblock %}
{% block aasemble_content %}
  {% for repository in repositories %}
  <h2>{{ repository.name }}</h2>
  <pre>
deb <a href="{{ repository.base_url }}">{{ repository.base_url }}</a> {{ repository.first_series.name }} main
deb-src <a href="{{ repository.base_url }}">{{ repository.base_url }}</a> {{ repository.first_series.name }} main
  </pre>
  <h3>Sources:</h3>
  <div class="table-responsive">
    <table class="table table-striped">
        <tr>
          <th>URL</th>
          <th>Branch</th>
        </tr>
      </thead>
      <tbody>
        {% for source in repository.first_series.sources.all %}
        <tr>
          <td><a href="{{ source.git_url }}">{{ source.git_url }}</a></td>
          <td>{{ source.branch }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% endfor %}
{% endblock %}

aasemble/django/apps/buildsvc/templates/buildsvc/html/sources.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}Package Sources{% endblock %}
{% block aasemble_content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Edit</th>
          <th>Enabled</th>
          <th>Rebuild</th>
          <th>Repository</th>
          <th>Branch</th>
          <th>Destination APT repo</th>
          <th>Last built commit</th>
        </tr>
      </thead>
      <tbody>
        {% for source in sources %}
        <tr>
          <td><small><a href="{% url "buildsvc:package_source" source_id=source.id %}">{% bootstrap_icon "pencil" %}</a></small></td>
          <td>
              {% if source.disabled %}
                {% bootstrap_icon "ban-circle" %}
              {% else %}
                {% bootstrap_icon "ok-circle" %}
              {% endif %}
              {% if source.disabled %}
                  <small><a href="{% url "buildsvc:enable_source_repo" source_id=source.id %}" role="button">{% bootstrap_icon "repeat" %} Enable</a></small>
              {% endif %}
          </td>
          <td><small><center><a href="{% url "buildsvc:rebuild" source_id=source.id %}">{% bootstrap_icon "repeat" %}</a></center></small></td>
          <td><a href="{{ source.git_url }}">{{ source.git_url }}</a></td>
          <td><a href="{{ source.git_url }}/tree/{{ source.branch }}">{{ source.branch }}</a></td>
          <td><a href="#">{{ source.series }}</a></td>
          <td>
              {% if source.last_seen_revision == None %}
                  None
              {% else %}
                  {% with source.git_url|add:"/commit/"|add:source.last_seen_revision as last_commit_url %}
                  <a href="{{ last_commit_url }}">{{ source.last_seen_revision|truncatechars:9 }}</a>
                  {% endwith %}
              {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  <a class="btn btn-primary" href="{% url "buildsvc:package_source" source_id='new' %}" role="button">{% bootstrap_icon "plus" %} New</a>
{% endblock %}