aasemble/django/apps/mirrorsvc/urls.py
from django.conf.urls import url

import aasemble.django.apps.mirrorsvc.views

urlpatterns = [
    url(r'^mirrors/(?P<mirror_uuid>[^/]+|new)/$', aasemble.django.apps.mirrorsvc.views.mirror_definition,
        name='mirror_definition'),  # Added before mirrors/ to override next line
    url(r'^mirrors/(?P<mirror_uuid>[^/]+)/refresh/', aasemble.django.apps.mirrorsvc.views.refresh_mirror_with_uuid,
        name='mirror_refresh'),  # Added before mirrors/ to override next line
    url(r'^mirrors/', aasemble.django.apps.mirrorsvc.views.mirrors, name='mirrors'),
    url(r'^snapshots/(?P<snapshot_uuid>[^/]+)/tags/(?P<tag_id>[^/]+|new)', aasemble.django.apps.mirrorsvc.views.snapshot_add_tag, name='snapshot_add_tag'),
    url(r'^snapshots/', aasemble.django.apps.mirrorsvc.views.snapshots, name='snapshots'),
    url(r'^mirrorsets/(?P<uuid>[^/]+|new)/$', aasemble.django.apps.mirrorsvc.views.mirrorset_definition,
        name='mirrorset_definition'),
    url(r'^mirrorsets/(?P<uuid>[^/]+)/snapshots/$', aasemble.django.apps.mirrorsvc.views.mirrorset_snapshots, name='mirrorset_snapshots'),
    url(r'^mirrorsets/(?P<uuid>[^/]+)/snapshots/new', aasemble.django.apps.mirrorsvc.views.create_new_snapshot, name='new_snapshot'),
    url(r'^mirrorsets/', aasemble.django.apps.mirrorsvc.views.mirrorsets, name='mirrorsets'),
]

test_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import django.contrib.auth.views
import aasemble.django.apps.main.views


urlpatterns = [
    url(r'^api/', include('aasemble.django.apps.api.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/$', aasemble.django.apps.main.views.profile, name='profile'),
    url(r'^$', aasemble.django.apps.main.views.index, name='index'),
    url(r'^buildsvc/', include('aasemble.django.apps.buildsvc.urls', namespace='buildsvc')),
    url(r'^mirrorsvc/', include('aasemble.django.apps.mirrorsvc.urls', namespace='mirrorsvc')),
    url(r'^logout/', django.contrib.auth.views.logout, {'next_page': '/'}, name='logout'),
]

aasemble/django/apps/mirrorsvc/models.py
import logging
import os.path
import uuid

from django.conf import settings
from django.contrib.auth import models as auth_models
from django.core.urlresolvers import reverse
from django.db import models
from django.template.loader import render_to_string
from django.utils.encoding import python_2_unicode_compatible

from six.moves.urllib.parse import urlparse

from aasemble.django.apps.mirrorsvc import tasks
from aasemble.utils import ensure_dir, run_cmd

LOG = logging.getLogger(__name__)


class MirrorSet(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    owner = models.ForeignKey(auth_models.User)
    mirrors = models.ManyToManyField('Mirror')
    extra_admins = models.ManyToManyField(auth_models.Group)

    @classmethod
    def lookup_by_user(cls, user):
        if not user.is_active:
            return cls.objects.none()
        if user.is_superuser:
            return cls.objects.all()
        return cls.objects.filter(owner=user) | cls.objects.filter(extra_admins=user.groups.all())

    @property
    def snapshots_url(self):
        # print(self.uuid)
        str_uuid = str(self.uuid)
        return reverse('mirrorsvc:mirrorset_snapshots', kwargs={'uuid': str_uuid})

    @property
    def sources_list(self):
        return '\n'.join([mirror.sources_list for mirror in self.mirrors.all()])

    def user_can_modify(self, user):
        return user == self.owner


@python_2_unicode_compatible
class Mirror(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    owner = models.ForeignKey(auth_models.User)
    url = models.URLField(max_length=200)
    series = models.CharField(max_length=200)
    components = models.CharField(max_length=200)
    public = models.BooleanField(default=False)
    refresh_in_progress = models.BooleanField(default=False)
    extra_admins = models.ManyToManyField(auth_models.Group)
    visible_to_v1_api = models.BooleanField(default=False)

    def __str__(self):
        return '<Mirror of %s (owner=%s)>' % (self.url, self.owner)

    def series_list(self):
        return self.series.split(' ')

    def get_config(self):
        return render_to_string('buildsvc/apt-mirror.conf',
                                {'mirror': self})

    def write_config(self):
        with open('%s/mirror.conf' % (self.basepath,), 'w') as fp:
            fp.write(self.get_config())

    @property
    def basepath(self):
        d = os.path.join(settings.MIRRORSVC_BASE_PATH, 'mirrors', str(self.uuid))
        if not os.path.isdir(d):
            os.makedirs(d)
            if self.visible_to_v1_api:
                os.symlink(d, os.path.join(settings.MIRRORSVC_BASE_PATH, 'mirrors', str(self.id)))
        return d

    @property
    def archive_dir(self):
        return ensure_dir(os.path.join(self.basepath, self.archive_subpath))

    @property
    def archive_subpath(self):
        parsed_url = urlparse(self.url)
        return os.path.join(parsed_url.netloc, parsed_url.path[1:])

    @property
    def sources_list(self):
        rv = ''
        parsed_url = urlparse(self.url)
        url = '%s/%s/%s%s' % (settings.MIRRORSVC_BASE_URL, self.uuid, parsed_url.netloc, parsed_url.path)
        for series in self.series_list():
            rv += 'deb %s %s %s\n' % (url, series, self.components)
            rv += 'deb-src %s %s %s\n' % (url, series, self.components)
        return rv

    @property
    def dists(self):
        return os.path.join(self.archive_dir, 'dists')

    @property
    def pool(self):
        return os.path.join(self.archive_dir, 'pool')

    @classmethod
    def lookup_by_user(cls, user):
        if not user.is_active:
            return cls.objects.none()
        if user.is_superuser:
            return cls.objects.all()
        return cls.objects.filter(owner=user) | cls.objects.filter(extra_admins=user.groups.all())

    def schedule_update_mirror(self):
        if Mirror.objects.filter(id=self.id, refresh_in_progress=False).update(refresh_in_progress=True) > 0:
            tasks.refresh_mirror.delay(self.id)
            return True
        else:
            # Update already scheduled
            return False

    def update_mirror(self):
        self.write_config()
        try:
            run_cmd(['apt-mirror', 'mirror.conf'], cwd=self.basepath, logger=self.logger)
        finally:
            Mirror.objects.filter(id=self.id).update(refresh_in_progress=False)

    def user_can_modify(self, user):
        return user == self.owner

    @property
    def logger(self):
        logpath = self.logpath()

        logger = logging.getLogger('mirrorsvc.update_mirror.%s' % self.uuid)
        logger.setLevel(logging.DEBUG)

        for handler in logger.handlers:
            logger.removeHandler(handler)

        formatter = logging.Formatter('%(asctime)s: %(message)s')
        logfp = logging.FileHandler(logpath)
        logfp.setLevel(logging.DEBUG)
        logfp.setFormatter(formatter)

        logger.addHandler(logfp)

        return logger

    def logfilename(self):
        LOG.debug('Determining config logfile name for mirror %s.' % (self.uuid))
        path = os.path.join('mirror_%s.log' % (self.uuid))

        return path

    def logpath(self):
        path = os.path.join(self.basepath, self.logfilename())  # basepath is gauranteed to exist, so no need to check and create

        return path

    def log_url(self):
        return '%s/%s/%s' % (settings.MIRRORSVC_BASE_URL, self.uuid, self.logpath())


@python_2_unicode_compatible
class Architecture(models.Model):
    name = models.CharField(max_length=50)
    apt_mirror_prefix = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Snapshot(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    mirrorset = models.ForeignKey(MirrorSet)
    visible_to_v1_api = models.BooleanField(default=False)

    @property
    def basepath(self):
        d = os.path.join(settings.MIRRORSVC_BASE_PATH, 'snapshots', str(self.uuid))
        if not os.path.isdir(d):
            os.makedirs(d)
            if self.visible_to_v1_api:
                os.symlink(d, os.path.join(settings.MIRRORSVC_BASE_PATH, 'snapshots', str(self.id)))
        return d

    def sync_dists(self):
        for mirror in self.mirrorset.mirrors.all():
            destdir = os.path.join(self.basepath, mirror.archive_subpath)
            if not os.path.exists(destdir):
                os.makedirs(destdir)
            run_cmd(['rsync', '-aHAPvi', '--exclude=**/i18n', mirror.dists, destdir])

    def symlink_pool(self):
        for mirror in self.mirrorset.mirrors.all():
            destdir = os.path.join(self.basepath, mirror.archive_subpath, 'pool')
            if not os.path.exists(destdir):
                os.symlink(mirror.pool, destdir)

    def save(self, *args, **kwargs):
        perform_snapshot = False

        if self.pk is None:
            perform_snapshot = True

        super(Snapshot, self).save(*args, **kwargs)

        if perform_snapshot:
            tasks.perform_snapshot.apply_async((self.id,), countdown=5)

    def perform_snapshot(self):
        self.sync_dists()
        self.symlink_pool()

    def user_can_modify(self, user):
        return user == self.mirrorset.owner


class Tags(models.Model):
    snapshot = models.ForeignKey(Snapshot, related_name='tags')
    tag = models.CharField(max_length=200)

    class meta:
        unique_together = ('snapshot', 'tag',)

    def save(self, *args, **kwargs):
        self.tag = self.tag.strip()
        super(Tags, self).save(*args, **kwargs)

    def user_can_modify(self, user):
        return self.snapshot.user_can_modify(user)

aasemble/django/apps/mirrorsvc/forms.py
from django.forms import ModelForm

from aasemble.django.apps.mirrorsvc.models import Mirror, MirrorSet, Tags


class MirrorDefinitionForm(ModelForm):
    class Meta:
        model = Mirror
        fields = ['url', 'series', 'components', 'public']


class MirrorSetDefinitionForm(ModelForm):
    class Meta:
        model = MirrorSet
        fields = ['name', 'mirrors']


class TagDefinitionForm(ModelForm):
    class Meta:
        model = Tags
        fields = ['tag']

aasemble/django/apps/mirrorsvc/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

from .forms import MirrorDefinitionForm, MirrorSetDefinitionForm, TagDefinitionForm
from .models import Mirror, MirrorSet, Snapshot, Tags


def get_mirror_definition_form(request, *args, **kwargs):
    form = MirrorDefinitionForm(*args, **kwargs)
    return form


@login_required
def mirror_definition(request, mirror_uuid):
    if mirror_uuid == 'new':
        mirror = None
    else:
        mirror = Mirror.objects.get(uuid=mirror_uuid)
        if not mirror.user_can_modify(request.user):
            mirror, mirror_uuid = None, 'new'

    if request.method == 'POST':
        form = get_mirror_definition_form(request, request.POST, instance=mirror)

        if mirror is not None and request.POST.get('delete', '') == 'delete':
            mirror.delete()
            return HttpResponseRedirect(reverse('mirrorsvc:mirrors'))

        if form.is_valid():
            new_mirror = form.save(commit=False)
            new_mirror.owner = request.user
            new_mirror.save()
            return HttpResponseRedirect(reverse('mirrorsvc:mirrors'))
    else:
        form = get_mirror_definition_form(request, instance=mirror)

    return render(request, 'mirrorsvc/html/mirror_definition.html',
                  {'form': form, 'mirror_uuid': mirror_uuid})


def get_mirrorset_definition_form(request, *args, **kwargs):
    form = MirrorSetDefinitionForm(*args, **kwargs)
    return form


@login_required
def mirrorset_definition(request, uuid):
    if uuid == 'new':
        mirrorset = None
    else:
        mirrorset = MirrorSet.objects.get(uuid=uuid)
        if not mirrorset.user_can_modify(request.user):
            mirrorset, uuid = None, 'new'

    if request.method == 'POST':
        form = get_mirrorset_definition_form(request, request.POST, instance=mirrorset)

        if mirrorset is not None and request.POST.get('delete', '') == 'delete':
            mirrorset.delete()
            return HttpResponseRedirect(reverse('mirrorsvc:mirrorsets'))

        if form.is_valid():
            new_mirrorset = form.save(commit=False)
            new_mirrorset.owner = request.user
            new_mirrorset.save()
            return HttpResponseRedirect(reverse('mirrorsvc:mirrorsets'))
    else:
        form = get_mirrorset_definition_form(request, instance=mirrorset)

    return render(request, 'mirrorsvc/html/mirrorset_definition.html',
                  {'form': form, 'uuid': uuid})


@login_required
def mirrors(request):
    mirrors = Mirror.lookup_by_user(request.user)
    return render(request, 'mirrorsvc/html/mirrors.html',
                  {'mirrors': mirrors})


@login_required
def snapshots(request):
    snapshots = Snapshot.objects.filter(mirrorset__in=MirrorSet.lookup_by_user(request.user)).order_by('timestamp')
    return render(request, 'mirrorsvc/html/snapshots.html',
                  {'snapshots': snapshots})


def get_tag_definition_form(request, *args, **kwargs):
    form = TagDefinitionForm(*args, **kwargs)
    return form


@login_required
def snapshot_add_tag(request, snapshot_uuid, tag_id):
    snapshot = Snapshot.objects.get(uuid=snapshot_uuid)
    if not snapshot.user_can_modify(request.user):
        return HttpResponse("You don't have access rights to add a tag to this snapshot")

    if tag_id == 'new':
        tag = None
    else:
        tag = Tags.objects.get(pk=tag_id)

    if request.method == 'POST':
        form = get_tag_definition_form(request, request.POST, instance=tag)

        if tag is not None and request.POST.get('delete', '') == 'delete':
            tag.delete()
            return HttpResponseRedirect(reverse('mirrorsvc:snapshots'))

        if form.is_valid():
            new_tag = form.save(commit=False)
            new_tag.snapshot = snapshot
            new_tag.save()
            return HttpResponseRedirect(reverse('mirrorsvc:snapshots'))
    else:
        form = get_tag_definition_form(request, instance=tag)

    return render(request, 'mirrorsvc/html/tag_definition.html',
                  {'form': form, 'snapshot_uuid': snapshot.uuid, 'tag_id': tag_id})


@login_required
def mirrorsets(request):
    sets = MirrorSet.lookup_by_user(request.user)
    return render(request, 'mirrorsvc/html/mirrorsets.html',
                  {'mirrorsets': sets})


@login_required
def mirrorset_snapshots(request, uuid):
    # print "Entered mirrorset_snapshots function"
    snapshots = list()
    try:
        mirrorset = MirrorSet.objects.get(uuid=uuid)
        snapshots = Snapshot.objects.filter(mirrorset=mirrorset)
    except:
        pass
    return render(request, 'mirrorsvc/html/mirrorset_snapshots.html',
                  {'snapshots': snapshots, 'mirrorset': mirrorset})


@login_required
def refresh_mirror_with_uuid(request, mirror_uuid):
    mirror = Mirror.objects.get(uuid=mirror_uuid)
    if mirror.user_can_modify(request.user):
        mirror.schedule_update_mirror()
    return HttpResponseRedirect(reverse('mirrorsvc:mirrors'))


@login_required
def create_new_snapshot(request, uuid):
    ms = MirrorSet.objects.get(uuid=uuid)
    if ms.user_can_modify(request.user):
        snap = Snapshot.objects.create(mirrorset=ms)
        snap.perform_snapshot()
    return HttpResponseRedirect(reverse('mirrorsvc:mirrorset_snapshots', kwargs={'uuid': uuid}))

aasemble/django/apps/mirrorsvc/templates/mirrorsvc/html/mirror_definition.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}
{% block title %}
    {% if mirror_id != 'new' %}
        Edit Mirror
    {% else %}
        Add new Mirror
    {% endif %}
{% endblock %}
{% block aasemble_content %}
<form action="{% url "mirrorsvc:mirror_definition" mirror_uuid=mirror_uuid %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
        {% if mirror_id != 'new' %}
            <button type="submit" class="btn btn-danger" name="delete" value="delete">
                 Delete
            </button>
        {% endif %}
    {% endbuttons %}
{% endblock %}

aasemble/django/apps/mirrorsvc/templates/mirrorsvc/html/mirrors.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}Mirrors{% endblock %}
{% block aasemble_content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>UUID</th>
          <th>URL</th>
          <th>Series</th>
          <th>Components</th>
          <th>Public</th>
          <th>Currently being Refreshed?</th>
          <th>Refresh Mirror?</th>
        </tr>
      </thead>
      <tbody>
      {% for mirror in mirrors %}
        <tr>
          <td><a href="{% url "mirrorsvc:mirror_definition" mirror_uuid=mirror.uuid %}">{{ mirror.uuid }}</a></td>
          <td><a href="{{ mirror.url }}">{{ mirror.url }}</a></td>
          <td>{{ mirror.series }}</td>
          <td>{{ mirror.components }}</td>
          <td>{{ mirror.public }}</td>
          <td>{{ mirror.refresh_in_progress }}</td>
          <td><a class="btn btn-default" href="{% url "mirrorsvc:mirror_refresh" mirror_uuid=mirror.uuid %}" role="button">{% bootstrap_icon "refresh" %} Refresh</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
    <a class="btn btn-primary" href="{% url "mirrorsvc:mirror_definition" mirror_uuid='new' %}" role="button">{% bootstrap_icon "plus" %} New</a>
{% endblock %}

aasemble/django/apps/mirrorsvc/templates/mirrorsvc/html/mirrorset_definition.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}
{% block title %}
    {% if uuid != 'new' %}
        Edit MirrorSet
    {% else %}
        Add new MirrorSet
    {% endif %}
{% endblock %}
{% block aasemble_content %}
<form action="{% url "mirrorsvc:mirrorset_definition" uuid=uuid %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
        {% if uuid != 'new' %}
            <button type="submit" class="btn btn-danger" name="delete" value="delete">
                 Delete
            </button>
        {% endif %}
    {% endbuttons %}
{% endblock %}

aasemble/django/apps/mirrorsvc/templates/mirrorsvc/html/mirrorset_snapshots.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}Snapshots for MirrorSet: {{ mirrorset.name }}{% endblock %}
{% block aasemble_content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Snapshot UUID</th>
          <th>Time Created</th>
          <th>Tags</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for snapshot in snapshots %}
        <tr>
          <td>{{ snapshot.uuid }}</td>
          <td>{{ snapshot.timestamp }}</td>
          <td>
              {% for tag in snapshot.tags.all %}
                  <a href="{% url "mirrorsvc:snapshot_add_tag" snapshot_uuid=snapshot.uuid tag_id=tag.id %}">{{ tag.tag }} </a>
              {% endfor %}
          </td>
          <td><a class="btn btn-default" href="{% url "mirrorsvc:snapshot_add_tag" snapshot_uuid=snapshot.uuid tag_id='new' %}" role="button">{% bootstrap_icon "plus" %} Add tag</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
    <a class="btn btn-primary" href="{% url "mirrorsvc:new_snapshot" uuid=mirrorset.uuid %}" role="button">{% bootstrap_icon "plus" %} Take new snapshot</a>
{% endblock %}

aasemble/django/apps/mirrorsvc/templates/mirrorsvc/html/mirrorsets.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}Mirror-Sets{% endblock %}
{% block aasemble_content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Mirror-Set UUID</th>
          <th>Name</th>
          <th>Snapshots</th>
        </tr>
      </thead>
      <tbody>
      {% for set in mirrorsets %}
        <tr>
          <td><a href="{% url "mirrorsvc:mirrorset_definition" uuid=set.uuid %}">{{ set.uuid }}</a></td>
          <td>{{ set.name }}</td>
          <td><a href="{{ set.snapshots_url }}">View snapshots</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
    <a class="btn btn-primary" href="{% url "mirrorsvc:mirrorset_definition" uuid='new' %}" role="button">{% bootstrap_icon "plus" %} New</a>
{% endblock %}

aasemble/django/apps/mirrorsvc/templates/mirrorsvc/html/snapshots.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}

{% block title %}Snapshots{% endblock %}
{% block aasemble_content %}
  <div class="table-responsive">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Mirror-Set UUID</th>
          <th>Mirror-Set Name</th>
          <th>Snapshot UUID</th>
          <th>Time Created</th>
          <th>Tags</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
      {% for snapshot in snapshots %}
        <tr>
          <td>{{ snapshot.mirrorset.uuid }}</td>
          <td>{{ snapshot.mirrorset.name }}</td>
          <td>{{ snapshot.uuid }}</td>
          <td>{{ snapshot.timestamp }}</td>
          <td>
              {% for tag in snapshot.tags.all %}
                  <a href="{% url "mirrorsvc:snapshot_add_tag" snapshot_uuid=snapshot.uuid tag_id=tag.id %}">{{ tag.tag }} </a>
              {% endfor %}
          </td>
          <td><a class="btn btn-default" href="{% url "mirrorsvc:snapshot_add_tag" snapshot_uuid=snapshot.uuid tag_id='new' %}" role="button">{% bootstrap_icon "plus" %} Add tag</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

aasemble/django/apps/mirrorsvc/templates/mirrorsvc/html/tag_definition.html
{% extends 'aasemble/base.html' %}
{% load bootstrap3 %}
{% block title %}
    {% if tag_id != 'new' %}
        Edit Tag
    {% else %}
        Add new Tag
    {% endif %}
{% endblock %}
{% block aasemble_content %}
<form action="{% url "mirrorsvc:snapshot_add_tag" snapshot_uuid=snapshot_uuid tag_id=tag_id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
        {% if tag_id != 'new' %}
            <button type="submit" class="btn btn-danger" name="delete" value="delete">
                 Delete
            </button>
        {% endif %}
    {% endbuttons %}
{% endblock %}